# Generated by Django 5.0.7 on 2024-08-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_remove_user_username_user_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='токен'),
        ),
    ]
